### ISSUE TITLE
Add DeletedAt column to the entity

### ISSUE THREAD

**Issue by angrave** [classtranscribe/WebAPI#123]
Add new columsn DeletedAt and DeletedBy to all entities.
Run PM add integration

And Add add line of code or two to 
https://github.com/classtranscribe/WebAPI/blob/50cb4b943d881f92e8adecdf298da04b2ddac7d6/ClassTranscribeDatabase/CTDbContext.cs#L277
to update these columns before saving

**Comment by SISEP7** [comment]
What does "Run PM add integration" mean?

**Comment by angrave** [comment]
In Visual Studio (not Code) use the PM window (package manager), select the correct project (database), and type "add integration name" where name is a lowercase name with no spaces (maybe underscores are okay though).
The package manager will then notice that 'deletedat' and deletedby' columns now exist and generate SQL ALTER commands that will run the next time we start the project.

**Comment by SISEP7** [comment]
I used to do a migration with "dotnet ef migrations add xxx" and then "dotnet ef database update". Is there a preferred way?

**Comment by angrave** [comment]
Good to know there’s an alternative that does not require Visual Code!

I believe the 2nd command is probably unnecessary; as the migrations will be performed if either the frontend or the taskengine are (re)started.

Personally I prefer the idea of explicitly updating the database independently of the both;maybe we should change the code at some point!


Lawrence Angrave
Teaching Professor, Department of Computer Science
CITL Teaching Fellow
University of Illinois at Urbana-Champaign (UIUC)
T: 217 333 1424  E: angrave@illinois.edu
