### ISSUE TITLE
Filter out duplicates in /api/WatchHistories/GetAllWatchedMediaForUser

### ISSUE THREAD

**Issue by ruihuasui** [classtranscribe/WebAPI#126]
The api `/api/WatchHistories/GetAllWatchedMediaForUser` returns many duplicate media, should only contain the latest modified one

<img width="685" alt="Screen Shot 2020-10-07 at 01 55 18" src="https://user-images.githubusercontent.com/42680819/95385688-f0f9c100-08b3-11eb-8502-7e497c04559a.png">

**Comment by angrave** [comment]
So something like GroupBy media, then select the first one-
https://stackoverflow.com/questions/19012986/how-to-get-first-record-in-each-group-using-linq
Playlists are made up of Media. A media (I believe) can only be in one playlist.

(Note on the serverside a video entity can appear more than once - it could be referenced in multiple media i.e. multiple playlists)
Also a media could have no Video (e.g. mp4 was missing when I tried to get it)
I suppose a Media could be more than once in a playlist? I believe not, but a quick check of the schema should prove that.
(note often a "video" on the frontend is actually a media entity)

**Comment by angrave** [comment]
Does this also mean the insertion of things into the watchlist is also buggy? Should it be updating a row if possible rather than inserting a row?

**Comment by ruihuasui** [comment]
Yeah, I think updating the column could be more straightforward.

**Comment by asherdale** [comment]
I can't seem to find a bug in the `PostWatchHistory` method. It could be some obscure EF bug that is hard to find. In any case, I'll fix this by only returning the latest modified watch history for any given media.
