### ISSUE TITLE
Video Watch Page; small UI bugs

### ISSUE THREAD

**Issue by angrave** [classtranscribe/WebAPI#17]
Various video watch bugs - 
(paraphrased) "When a monitor is set to 16:9 (but not 16:10),CT crops the top and bottom of the videos."
(Suggest Test in full screen mode and reproduce this bug before trying to fix it).

"Have an easy way to navigate from one playlist to the next. Currently you have to go back to the home page and refind the course, and select the next playlist.

Speed selector issues.  If I view part 1 of a lecture, when I go to part 2 the speed is not correct.  It displays the speed as still faster, but it the video only plays at 1X speed.

Can't rewind from 9 or less seconds back to the 0 by arrow keys.  To prevent going negative, it doesn't seek.  It should seek back to 0.
"

**Comment by ruihuasui** [comment]
All these issues are fixed in the FrontEnd PR [#56](https://github.com/classtranscribe/FrontEnd/pull/56)
