### ISSUE TITLE
TaskEngine won't build on Mac OS Big Sur

### ISSUE THREAD

**Issue by houyuan2** [classtranscribe/WebAPI#170]
Python RPC server (grpc) won't build outside Docker container on Mac OS Big Sur. When building TaskEngine via Visual Studio, Nuget grpc packages would fail and kill the build process. Example issue: https://github.com/grpc/grpc/issues/24760

It is recommended that developers on Mac should use Catalina OS to avoid such problems.

**Comment by angrave** [comment]
I assume building using Docker though is okay on a Mac with Big Sur?

**Comment by houyuan2** [comment]
Yes, Docker still works on Big Sur
