### ISSUE TITLE
Signout of Auth0 when signing out of ClassTranscribe

### ISSUE THREAD

**Issue by angrave** [classtranscribe/WebAPI#21]
Auth0 caches credentials; so it is not possible to sign in as someone else without using a new private window.

**Comment by angrave** [comment]
Probably just need to clear the auth0 cookie - 
https://auth0.com/docs/logout

**Comment by asherdale** [comment]
@angrave is this still an issue? Was not able to reproduce on my local setup (fullstack on mac) or on the production site. Could someone else verify so we can close the issue (or investigate further if not able to reproduce)?

**Comment by angrave** [comment]
I logged in using my personal gmail then logged out. I could not reproduce either on Chrome. So I'll close this out
