### ISSUE TITLE
Youtube Channels

### ISSUE THREAD

**Issue by chirantan31** [classtranscribe/WebAPI#23]
Only downloading from Youtube Playlists is supported currently. Support downloading from Youtube Channels

**Comment by angrave** [comment]
Youtube channels now supported in the backend but the frontend does not accept channel URL.

Example valid channel URLs-

https://www.youtube.com/channel/UCnke9ArO0djAccZgmR1XGkg
https://www.youtube.com/channel/UCnke9ArO0djAccZgmR1XGkg/videos

The Backend expects "isChannel" json in metadata field to be set to "1" and the id to be unique channel ID.
https://github.com/classtranscribe/WebAPI/blob/master/PythonRpcServer/youtube.py#L23

Alternatively we could bring this into alignment with Kaltura and set the source id field to be one of the following formats
youtube.com/channel/id
youtube.com/playlist/id

**Comment by asherdale** [comment]
Closing because fixed on backend. Made corresponding issue for frontend: https://github.com/classtranscribe/FrontEnd/issues/228
