### ISSUE TITLE
Add NOT NULL constraints and default values for all JObject fields

### ISSUE THREAD

**Issue by asherdale** [classtranscribe/WebAPI#255]
The following columns should have NOT NULL constraints in their respective DB tables, as well as default values in the C# backend:

- ApplicationUser.Metadata
- Offering.JsonMetadata
- Playlist.JsonMetadata
- Media.JsonMetadata
- Log.Json
- EPub.Cover
- WatchHistory.Json
- Message.Payload
- TaskItem.TaskParameters
- TaskItem.ResultData
- TaskItem.RemoteResultData

@angrave these are all of the JObject fields across all different kinds of entities (besides the JObject fields in the Video entity, which have already been taken care of). Are there any other fields for which you would like me to add NOT NULL constraints + default values?

**Comment by angrave** [comment]
That should be fine. The Entity class definitions rarely have nullable ("type?") fields; so in practice these should all contain (non-null) data.
