### ISSUE TITLE
Fix the repercussion of implementing Soft-Delete

### ISSUE THREAD

**Issue by chirantan31** [classtranscribe/WebAPI#32]
Because of the Soft-Delete feature used by ClassTranscribe, no row is ever deleted from the database, but rather is marked as inactive. This creates an issue when an already "deleted" row is added again in which case there occurs a key conflict.

**Comment by tdy** [comment]
Fixed by #61

**Comment by tdy** [comment]
Reopening:

> Unfortunately we had to revert this PR because the migration failed on a -dev; A null pointer in a many-many table stopped the migration update from completing. We need to re-open this.
> 
> _Originally posted by @angrave in https://github.com/classtranscribe/WebAPI/pull/61#issuecomment-694280427_
