### ISSUE TITLE
Request for a new API: get all the offerings for an instructor

### ISSUE THREAD

**Issue by ruihuasui** [classtranscribe/WebAPI#48]
The current API the frontend is using to get all the offerings of an instructor is `/api/CourseOfferings/ByInstructor/{userId}`. This API grouped the offerings by courses, but for the new interface this grouping is not needed any more and could cause even more works to parse the data. 

So we want to request a new API `/api/Offerings/ByInstructor` just like `/api/Offerings/ByStudent`, that returns all the offerings for an instructor in an **array** ordered by **created time**. Also, like the `/api/Offerings/ByStudent`, this API is expected to have the **term data and department data** inside each offering object.

The below is a single offering data obtained by calling `/api/Offerings/ByStudent`. It will be great that the `/api/Offerings/ByInstructor` can return similar ones.
<img width="477" alt="Screen Shot 2020-07-02 at 16 21 53" src="https://user-images.githubusercontent.com/42680819/86410301-28871a80-bc80-11ea-9c67-ec24ecfb505d.png">

**Comment by asherdale** [comment]
Hey @ruihuasui, do you still want this new endpoint? If so, I can build it.

Just to confirm, the output of the new endpoint will be almost identical to the `/ByStudent` endpoint. I am assuming that the only difference would be that the `instructorIds` array could be empty for the new endpoint, as you are querying by instructorID. Or would you still like me to include all of the instructorIDs for the offering in this array?

**Comment by ruihuasui** [comment]
> Hey @ruihuasui, do you still want this new endpoint? If so, I can build it.
> 
> 
> 
> Just to confirm, the output of the new endpoint will be almost identical to the `/ByStudent` endpoint. I am assuming that the only difference would be that the `instructorIds` array could be empty for the new endpoint, as you are querying by instructorID. Or would you still like me to include all of the instructorIDs for the offering in this array?

Hi @asherdale, yes this API would be really helpful. In addition to `instructorIds`, the courses objects also contain the `departmentAcronym` and there is a detailed `term` object as well.

**Comment by asherdale** [comment]
What should the authentication level be for this? Admins only, instructors only, or everyone?

**Comment by ruihuasui** [comment]
It should be accessible only for the instructor who send the request and admins.

**Comment by asherdale** [comment]
The `/api/Offerings/ByStudent` endpoint filters out offerings that don't have any media items (i.e. all of their playlists contain no media items). Do you want the same behavior for `/api/Offerings/ByInstructor`?

**Comment by ruihuasui** [comment]
Nope, instructors need to see all their courses.
