### ISSUE TITLE
Transcription language is hard-coded

### ISSUE THREAD

**Issue by houyuan2** [classtranscribe/WebAPI#56]
https://github.com/classtranscribe/WebAPI/blob/master/CTCommons/MSTranscription/MSTranscriptionService.cs
Line 51-55
The language setting for transcription is hard-coded. This could be moved into other setting files like the environment file.

**Comment by angrave** [comment]
Gotchas: 
The number of existing transcriptions in the database for a particular video may be more or less than the settings
Consider Restarts and timeouts
Consider full Replacements
Ensure frontend has a mechanism to enumerate complete transcriptions

Related: Be able to support multiple transcriptions from multiple sources e.g. embedded in mp4, separate download from kaltura, uploaded vtt/srt

**Comment by asherdale** [comment]
Fixed in #108 (default languages are still hardcoded but can be overridden by environment variables)
