### ISSUE TITLE
Having 405 when sign in

### ISSUE THREAD

**Issue by SiweiShen2019** [classtranscribe/WebAPI#85]
Hi developers,

I have the following issues when I sign in through UIUC shibboleth:

```
POST https://classtranscribe.illinois.edu/api/Account/SignIn 405
Failed to get user data and auth token from backend Error: Request failed with status code 405
    at e.exports (createError.js:17)
    at e.exports (settle.js:19)
    at XMLHttpRequest.f.onreadystatechange (xhr.js:63)
```

I wonder if there is anything I can do on my end to solve it.

**Comment by SiweiShen2019** [comment]
Sometimes the first 405 also shows as the following 

```
Failed to load resource: the server responded with a status of 405 () /api/Account/SignIn:1
```

**Comment by angrave** [comment]
The server was down. Please refresh your page. You might need to flush your local cache./open in a new private window
