### ISSUE TITLE
Understand and improve file creation by TaskEngine and WebAPI

### ISSUE THREAD

**Issue by angrave** [classtranscribe/WebAPI#90]
C# and python code create random files. e.g. the C# Code calls GetTmpFile() in CommonUtils.cs
Later these files may be renamed (e.g. an extension "vtt" is added) so the files are not actually temporary at all.

Other files are temporary and (as far I can tell!) may never be cleaned up (e.g. WAV files e.g. database dumps)

See also https://github.com/classtranscribe/WebAPI/issues/8

Related comments:
Should we create random filenames using  Guid.NewGuid() instead of the convoluted C# and something similar for python code?

**Comment by asherdale** [comment]
@angrave @robkooper it seems like it isn't possible to create `FilePath` values for existing Courses and CourseOfferings during a DB migration like I had initially planned. I am thinking that an alternative solution would be to create an endpoint (something like `/api/Admin/BackfillFilePaths`) that will look through all existing Courses and CourseOfferings in the DB and compute any missing `FilePath` fields. How does that sound?

Wiki page for reference: [https://github.com/classtranscribe/WebAPI/wiki/File-Creation](https://github.com/classtranscribe/WebAPI/wiki/File-Creation)

**Comment by angrave** [comment]
Sounds good. It should be restartable
i.e. bad things should not happen if it does not complete the first time and we need to rerun it. 
It should not change filepaths that have already been changed
It should return the total number of files that were updated.
